language: php

sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache/files

matrix:
    include:
        - php: hhvm-stable
          sudo: required
          dist: trusty
        - php: 7.0
        - php: 7.1
    allow_failures:
        - php: hhvm-stable
    fast_finish: true

before_install:
    - if [[ ! $TRAVIS_PHP_VERSION = hhvm* ]]; then phpenv config-rm xdebug.ini || echo "xdebug not available"; fi
    - if [[ $TRAVIS_PHP_VERSION = hhvm* ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi

install:
    - travis_retry composer install
