language: php

sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache/files

matrix:
    include:
        - php: hhvm-stable
          sudo: required
          dist: trusty
          env: TWIG_EXT=no
        - php: 7.0
          env: TWIG_EXT=no
        - php: 7.1
          env: TWIG_EXT=no
    allow_failures:
        - php: hhvm-stable
    fast_finish: true

before_install:
    - if [[ ! $TRAVIS_PHP_VERSION = hhvm* ]]; then phpenv config-rm xdebug.ini || echo "xdebug not available"; fi
    - if [[ $TRAVIS_PHP_VERSION = hhvm* ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi

install:
    - travis_retry composer install

before_script:
    - if [ "$TWIG_EXT" == "yes" ]; then sh -c "cd ext/twig && phpize && ./configure --enable-twig && make && make install"; fi
    - if [ "$TWIG_EXT" == "yes" ]; then echo "extension=twig.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`; fi
